### ISSUE TITLE
Running installation command fails

### ISSUE THREAD

**Issue by filip-cermak** [typesense/showcase-airbnb-geosearch#1]
## Description
Running installation command fails

## Steps to reproduce
clone,
yarn,
yarn start

## Expected Behavior

Running on localhost:5000

## Actual Behavior

yarn command throws:

```
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "instantsearch.js > algoliasearch-helper@3.6.2" has unmet peer dependency "algoliasearch@>= 3.1 < 5".
[5/5] Building fresh packages...
[1/4] ⠂ typesense-instantsearch-adapter
[2/4] ⠂ core-js
[3/4] ⠂ deasync
error /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync: Command failed.
Exit code: 1
Command: node ./build.js
Arguments: 
Directory: /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync
Output:
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
```

yarn start command throws:
```
yarn run v1.22.19
$ parcel index.html --port 3000
/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/Debug/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/Release/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/out/Debug/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/Debug/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/out/Release/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/Release/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/default/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/compiled/18.18.0/linux/x64/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/lib/binding/node-v108-linux-x64/deasync.node
    at bindings (/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/index.js:30:31)
    at Module._compile (/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/parcel-bundler/src/utils/syncPromise.js:1:79)
    at Module._compile (/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/v8-compile-cache/v8-compile-cache.js:192:30) {
  tries: [
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/Debug/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/Release/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/out/Debug/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/Debug/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/out/Release/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/Release/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/build/default/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/compiled/18.18.0/linux/x64/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/addon-build/release/install-root/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/addon-build/debug/install-root/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/addon-build/default/install-root/deasync.node',
    '/home/filipcermak/b/job-board/showcase-airbnb-geosearch/node_modules/deasync/lib/binding/node-v108-linux-x64/deasync.node'
  ]
}

Node.js v18.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Metadata

**Typesense Version**: No Typesense issue

**OS**: Linux, Pop OS 22.04

**Comment by jasonbosco** [comment]
This was due to parcel 1 not supporting Node 18. Fixed this in [16ae136](https://github.com/typesense/showcase-airbnb-geosearch/commit/16ae136dc47d84dea405d1b3fc3f03e23fb990ce). Could you try now after pulling the latest commits?
